### ISSUE TITLE
Session Credential Provider Unable to Refresh When Getting Exception

### ISSUE THREAD

**Issue by jiaheng** [aliyun/credentials-java#56]
The result of `refreshCallable.call()` can be null (see https://github.com/aliyun/credentials-java/blob/953d4ff8eb2396bdb0d391bd265139499106638e/src/main/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProvider.java#L165C7-L165C7), causing the cacheValue never being refreshed when it is being assigned to null.

Suggestion, consider cache is stale, when cachedValue is null.
https://github.com/aliyun/credentials-java/blob/953d4ff8eb2396bdb0d391bd265139499106638e/src/main/java/com/aliyun/credentials/provider/RefreshCachedSupplier.java#L112

* **JAVA Version**: 17
* **Platform**: 
* **Product**: OSS, RabbitMQ
* **Product Version**:
* **API**:

**Comment by TsinghuaDream** [comment]
Can you provide a reproduction scenario or more information?

**Comment by jiaheng** [comment]
@TsinghuaDream When there is a network issue (ie outage in Alibaba Cloud), the CredentialClient unable to refresh the credential, causing the value to be set as null. When this happens, subsequent refresh will failed due to null pointer exception. Here is some sample log:

```
com.aliyun.credentials.exception.CredentialException: Read timed out
	at com.aliyun.credentials.provider.OIDCRoleArnCredentialProvider.getNewSessionCredentials(OIDCRoleArnCredentialProvider.java:209)
	at com.aliyun.credentials.provider.OIDCRoleArnCredentialProvider.createCredential(OIDCRoleArnCredentialProvider.java:159)
	at com.aliyun.credentials.provider.OIDCRoleArnCredentialProvider.refreshCredentials(OIDCRoleArnCredentialProvider.java:154)
	at com.aliyun.credentials.provider.SessionCredentialsProvider$1.call(SessionCredentialsProvider.java:14)
	at com.aliyun.credentials.provider.SessionCredentialsProvider$1.call(SessionCredentialsProvider.java:11)
	at com.aliyun.credentials.provider.RefreshCachedSupplier.refreshCache(RefreshCachedSupplier.java:53)
	at com.aliyun.credentials.provider.RefreshCachedSupplier.blockingRefresh(RefreshCachedSupplier.java:67)
	at com.aliyun.credentials.provider.RefreshCachedSupplier.get(RefreshCachedSupplier.java:45)
	at com.aliyun.credentials.provider.SessionCredentialsProvider.getCredentials(SessionCredentialsProvider.java:35)
	at com.aliyun.credentials.Client.getCredential(Client.java:141)
	at com.xyz.rabbitmq.AliyunRabbitmqCredentialProvider.refresh(AliyunRabbitmqCredentialProvider.java:54)
	at com.rabbitmq.client.impl.DefaultCredentialsRefreshService$CredentialsProviderState.refresh(DefaultCredentialsRefreshService.java:334)
	at com.rabbitmq.client.impl.DefaultCredentialsRefreshService.lambda$refresh$1(DefaultCredentialsRefreshService.java:156)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)"
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

{
"@timestamp":"2024-02-10T07:42:03.951014993Z",
"message":"Error while trying to refresh a connection token",
"logger_name":"com.rabbitmq.client.impl.DefaultCredentialsRefreshService"
"stack_trace": "java.lang.NullPointerException: Cannot invoke "com.aliyun.credentials.models.CredentialModel.getAccessKeySecret()" because "this.credentialModel" is null
	at com.xyz.rabbitmq.AliyunRabbitmqCredentialProvider.generatePassword(AliyunRabbitmqCredentialProvider.java:101)
	at com.xyz.rabbitmq.AliyunRabbitmqCredentialProvider.getPassword(AliyunRabbitmqCredentialProvider.java:43)
	at com.rabbitmq.client.impl.AMQConnection.lambda$start$1(AMQConnection.java:465)
	at com.rabbitmq.client.impl.DefaultCredentialsRefreshService$CredentialsProviderState.refresh(DefaultCredentialsRefreshService.java:360)
	at com.rabbitmq.client.impl.DefaultCredentialsRefreshService.lambda$refresh$1(DefaultCredentialsRefreshService.java:156)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)"
}

Exception in thread "org.springframework.amqp.rabbit.RabbitListenerEndpointContainer#0-227" java.lang.NullPointerException: Cannot invoke "com.aliyun.credentials.models.CredentialModel.getAccessKeyId()" because "this.credentialModel" is null

```

**Comment by iOtter** [comment]
Hi @TsinghuaDream, I've seen the similar error (through RRSA in my case). It starts to throw NPE after some time (roughly a day or two I think). Restart my application temproraroly fixes the problem. Error logs:

```
java.lang.NullPointerException: null
at com.aliyun.credentials.provider.RefreshCachedSupplier.cacheIsStale(RefreshCachedSupplier.java:112)
at com.aliyun.credentials.provider.RefreshCachedSupplier.get(RefreshCachedSupplier.java:41)
at com.aliyun.credentials.provider.SessionCredentialsProvider.getCredentials(SessionCredentialsProvider.java:35)
at com.aliyun.credentials.provider.DefaultCredentialsProvider.getCredentials(DefaultCredentialsProvider.java:44)
at com.aliyun.credentials.Client.getAccessKeyId(Client.java:116)
```

Thanks for taking a look!

**Comment by yndu13** [comment]
该问题已修复
